on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on Aarch64
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v2.1.0
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu20.04
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
